services:
  spark:
    build: .
    container_name: spark-app
    environment:
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./jars/postgresql-42.5.4.jar:/opt/bitnami/spark/jars/postgresql-42.5.4.jar
    ports:
      - "4040:4040"
    command: >
      spark-submit
      --driver-class-path /opt/bitnami/spark/jars/postgresql-42.5.4.jar
      --jars /opt/bitnami/spark/jars/postgresql-42.5.4.jar
      src/ml_pipeline.py